# Generated by Django 3.2.12 on 2023-02-13 16:53

from django.db import migrations, models
import jobportal_cron.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('career_page', models.URLField()),
                ('job_openings', models.IntegerField(default=0)),
                ('logo', models.ImageField(storage=jobportal_cron.storage_backends.PublicMediaStorage, upload_to='companies/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
